---
title: "Contest-Interaction ABM Data Analysis -- Sigmoid Function Figures"
author: "C.J. O'Connor-Coates"
date: "2023-06-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


#-------------------------------------------------------------------------------------------------------------------------

# All data was generated in NetLogo Agent-Based Models (ABM) and imported into this program for analysis. These data and analyses are used in the publication "Steep hierarchies without skew? Modeling how ecology and decision-making shape despotism of relationships" by Marcy S. Ekanayake-Weber, Christopher J. O'Connor-Coates, and Andreas Koenig.

# The NetLogo model was created by Marcy S. Ekanayake-Weber and Christopher J. O'Connor-Coates. The following R-code was written by Christopher J. O'Connor-Coates. The code for the Triangle Transitivity Function was written by Shizuka & McDonald (2012). For questions regarding the R-code email Christopher J. O'Connor-Coates at christopher.oconnor-coates@stonybrook.edu.

#-------------------------------------------------------------------------------------------------------------------------

#-------------------------------------------------------------------------------------------------------------------------

# DEFINITIONS:
# 1. Knowledge (k): Individuals know of either their own or their opponent's Resource Holding Potential (RHP)
# 2. History (h): Individuals know of either their own or their opponent's fighting history, including how often theiy won or lost conflicts
# 3. Mutual (m): Individuals have knowledge of both their own and their opponent's RHP or History
# 4. Self (s): Individuals have knowledge of only their own RHP or History
# 5. Opponent (o): Individuals have knowledge of only their opponent's RHP or History
# 6. Deterministic (d): Scenarios in which fight outcomes were determined by the strength of an individual's RHP. Individuals with higher RHP values always won escalated conflicts.
# 7. Probabilistic (p): Scenarios in which fight outcomes were determined by a probability calculated in the NetLogo program. Individuals with higher RHP values are more likely to win escalated conflicts, but there is also a (smaller) chance that the individual with lower RHP could win the conflict.
# 8. Initiator Wins (iw; i): Scenarios in which the escalated conflict is always won by the individual which initiated the conflict.
# 9. Sigmoid Function (sf): Scenarios in which fights were escalated through a cost-benefit analysis that was modeled as a sigmoid function.
# 10. Clumped Distribution (cd; c): Resources were arranged in the landscape such that they only appeared in clumps; can also be called a heterogenous distribution
# 11. Uniform Distribution (ud; u): Resources were arranged in the landscape such that they were evenly distributed across the area; can also be called a homogenous distribution
# 12. Avoid: An individual avoided an escalation/conflict
# 13. Victory: An individual won an escalation/conflict
# 14. Foraging Efficiency: An Individual's Energy Intake Over Time

#ABBREVIATIONS:
# 1. inter.mat: Interaction Matrices
# 2. ep: Proportion of Escalation
# 3. t.tri: Triangle Transitivity
# 4. dci: Directional Conistency Index
# 5. Steep: steepness

#-------------------------------------------------------------------------------------------------------------------------


# DETERMINISTIC DATA FIGURES

##X-LABELS FOR FIGURES
## The below code creates an object that contains character names for graph X-axis labels.
x.lab<-c("Mutual History","Mutual History","Mutual RHP","Mutual RHP","Opponent History","Opponent History","Opponent RHP","Opponent RHP","Self History","Self History","Self RHP","Self RHP")


##PROPORTION OF ATTACK FIGURE
library(tidyverse)
library(ggplot2)
library(hrbrthemes)
library(viridis)
library(Rmisc)

setwd("~/Desktop")

sf.deter.prop_attack.fig<-attack.prop.sf.2 %>%
  ggplot( aes(x=combo2, y=as.numeric(proportion.attacking),color=resource.dist)) +
    geom_boxplot(outlier.shape=NA) +
    geom_point(aes(shape=resource.dist),size=2.5,position=position_dodge(width=0.75))+
    scale_shape_manual(values=c(1, 2))+
    xlab("")+
    ylab("Proportion of Attack") +
    theme_bw() +
    theme(panel.grid.major.x = element_line(color = "grey",size = 0.3,linetype = 2),legend.position="none",panel.grid.major = element_blank(), panel.grid.minor = element_blank(),axis.text.x=element_text(size=13, colour="black"),axis.text.y=element_text(size=12, colour="black"), panel.border=element_rect(colour="black", size=1, fill=NA), axis.title.y=element_text(size=14))+    
    scale_color_manual(values = c("blue","#CC5500")) +
    scale_x_discrete(limit=c("mutual rhp", "mutual history"), labels=c("RHP", "Experience"))  + 
    annotate(geom="text", x=c(1.5), y=0.05, label=c("Mutual"), size=5)+
    coord_cartesian(expand=F, clip="off", xlim=c(0.25, 2.75), ylim=c(0.1,0.65))
jpeg("sf.deter.prop_attack.fig.jpeg", 336, 336)
sf.deter.prop_attack.fig
dev.off()

sf.deter.prop_attack.fig



##RATE OF AVOIDS FIGURE
library(tidyverse)
library(ggplot2)
library(hrbrthemes)
library(viridis)
library(Rmisc)


setwd("~/Desktop")
rate.avoids.fig<-attack.prop.sf.2 %>%
  ggplot( aes(x=combo2, y=rate.avoids,color=resource.dist)) +
    geom_boxplot(outlier.shape=NA) +
    geom_point(aes(shape=resource.dist),size=2.5,position=position_dodge(width=0.75))+
    scale_shape_manual(values=c(1, 2))+
    xlab("")+
    ylab("Rate of Avoids") +
    theme_bw() +
    theme(panel.grid.major.x = element_line(color = "grey",size = 0.3,linetype = 2),legend.position="none",panel.grid.major = element_blank(), panel.grid.minor = element_blank(),axis.text.x=element_text(size=13, colour="black"),axis.text.y=element_text(size=12, colour="black"), panel.border=element_rect(colour="black", size=1, fill=NA), axis.title.y=element_text(size=14))+    
    scale_color_manual(values = c("blue","#CC5500")) +
    scale_x_discrete(limit=c("mutual rhp", "mutual history"), labels=c("RHP", "Experience"))  + 
    annotate(geom="text", x=c(1.5, 3.5, 5.5), y=-0.16, label=c("Mutual"), size=5)+
    coord_cartesian(expand=F, clip="off", xlim=c(0.25, 2.75), ylim=c(-0.1,0.65))
jpeg("rate.avoids.fig.jpeg", 336, 336)
rate.avoids.fig
dev.off()

rate.avoids.fig


##RATE OF ATTACKS FIGURE
library(tidyverse)
library(ggplot2)
library(hrbrthemes)
library(viridis)
library(Rmisc)


setwd("~/Desktop")
sf.rate.attacks.fig<-attack.prop.sf.2 %>%
  ggplot( aes(x=combo2, y=rate.attacks,color=resource.dist)) +
    geom_boxplot(outlier.shape=NA) +
    geom_point(aes(shape=resource.dist),size=2.5,position=position_dodge(width=0.75))+
    scale_shape_manual(values=c(1, 2))+
    xlab("")+
    ylab("Rate of Attacks") +
    theme_bw() +
    theme(panel.grid.major.x = element_line(color = "grey",size = 0.3,linetype = 2),legend.position="none",panel.grid.major = element_blank(), panel.grid.minor = element_blank(),axis.text.x=element_text(size=13, colour="black"),axis.text.y=element_text(size=12, colour="black"), panel.border=element_rect(colour="black", size=1, fill=NA), axis.title.y=element_text(size=14))+    
    scale_color_manual(values = c("blue","#CC5500")) +
    scale_x_discrete(limit=c("mutual rhp", "mutual history"), labels=c("RHP", "Experience"))  + 
    annotate(geom="text", x=c(1.5, 3.5, 5.5), y=-0.16, label=c("Mutual"), size=5)+
    coord_cartesian(expand=F, clip="off", xlim=c(0.25, 2.75), ylim=c(-0.1,0.65))
jpeg("sf.rate.attacks.fig.jpeg", 336, 336)
sf.rate.attacks.fig
dev.off()

sf.rate.attacks.fig
    



##TRIANGLE TRANSITIVIY FIGURE
setwd("~/Desktop")
addline_format <- function(x,...){
    gsub('\\s','\n',x)
}

sf.deter.TTri.fig <- overall.deter.sf %>%
  ggplot( aes(x=combo2, y=triangle.transitivity,color=distribution)) +
  geom_boxplot(outlier.shape=NA) +
    geom_point(aes(shape=distribution),size=2.5,position=position_dodge(width=0.75))+
    scale_shape_manual(values=c(1, 2))+
    xlab("")+
    ylab("Triangle Transitivity") +
    theme_bw() +
    theme(panel.grid.major.x = element_line(color = "grey",size = 0.3,linetype = 2),legend.position="none",panel.grid.major = element_blank(), panel.grid.minor = element_blank(),axis.text.x=element_text(size=13, colour="black"),axis.text.y=element_text(size=12, colour="black"), panel.border=element_rect(colour="black", size=1, fill=NA), axis.title.y=element_text(size=14))+    scale_color_manual(values = c("blue","#CC5500")) +
    scale_x_discrete(limit=c("mutual rhp", "mutual history"), labels=c("RHP", "Experience"))  + 
    annotate(geom="text", x=c(1.5), y=-0.15, label=c("Mutual"), size=5)+
    coord_cartesian(expand=F, clip="off", xlim=c(0.25, 2.75), ylim=c(-0.05, 1.05))
jpeg("sf.deter.TTri.fig.jpeg", 336, 336)
sf.deter.TTri.fig
dev.off()


##DIRECTIONAL CONSISTENCY INDEX FIGURE
sf.deter.DCI.fig <- overall.deter.sf %>%
  ggplot( aes(x=combo2, y=dci,color=distribution)) +
geom_boxplot(outlier.shape=NA) +
    geom_point(aes(shape=distribution),size=2.5,position=position_dodge(width=0.75))+
    scale_shape_manual(values=c(1, 2))+
    xlab("")+
    ylab("Directional Consistency Index") +
    theme_bw() +
    theme(panel.grid.major.x = element_line(color = "grey",size = 0.3,linetype = 2),legend.position="none",panel.grid.major = element_blank(), panel.grid.minor = element_blank(),axis.text.x=element_text(size=13, colour="black"),axis.text.y=element_text(size=12, colour="black"), panel.border=element_rect(colour="black", size=1, fill=NA), axis.title.y=element_text(size=14))+    scale_color_manual(values = c("blue","#CC5500")) +
    scale_x_discrete(limit=c("mutual rhp", "mutual history"), labels=c("RHP", "Experience"))  + 
    annotate(geom="text", x=c(1.5, 3.5, 5.5), y=-0.15, label=c("Mutual"), size=5)+
    coord_cartesian(expand=F, clip="off", xlim=c(0.25, 2.75), ylim=c(-0.05,1.05))
jpeg("sf.deter.DCI.fig.jpeg", 336, 336)
sf.deter.DCI.fig
dev.off()
  
  
##STEEPNESS FIGURE    
sf.deter.Steep.fig <- overall.deter.sf %>%
  ggplot( aes(x=combo2, y=abs(steepness),color=distribution)) +
  geom_boxplot(outlier.shape=NA) +
    geom_point(aes(shape=distribution),size=2.5,position=position_dodge(width=0.75))+
    scale_shape_manual(values=c(1, 2))+
    xlab("")+
    ylab("Steepness") +
    theme_bw() +
    theme(panel.grid.major.x = element_line(color = "grey",size = 0.3,linetype = 2),legend.position="none",panel.grid.major = element_blank(), panel.grid.minor = element_blank(),axis.text.x=element_text(size=13, colour="black"),axis.text.y=element_text(size=12, colour="black"), panel.border=element_rect(colour="black", size=1, fill=NA), axis.title.y=element_text(size=14))+    scale_color_manual(values = c("blue","#CC5500")) +
    scale_x_discrete(limit=c("mutual rhp", "mutual history"), labels=c("RHP", "Experience"))  + 
    annotate(geom="text", x=c(1.5, 3.5, 5.5), y=-0.15, label=c("Mutual"), size=5)+
    coord_cartesian(expand=F, clip="off", xlim=c(0.25, 2.75), ylim=c(-0.05,1.05))
jpeg("sf.deter.Steep.fig.jpeg", 336, 336)
sf.deter.Steep.fig
dev.off()

sf.deter.TTri.fig
sf.deter.DCI.fig
sf.deter.Steep.fig



##ENERGY EFFICIENCY FIGURE
setwd("~/Desktop")
jpeg("sf.deter.energy_efficiency.fig.jpeg", 672, 336)
par(cex.axis=1, cex.lab=1.3, mar=c(2.65,2.75,0.4,0.4),family="sans")
sf.deter.energy_efficiency.fig<-plot(total.energy.cp.sf$energy_over_time~total.energy.cp.sf$normDS,pch=1,cex=1.4,xaxt="n",yaxt="n",col="blue",xlab="",ylab="",main="",ylim=c(0.4,0.8),xlim=c(0.85,8.25),las=1); points(total.energy.pu.sf$energy_over_time~total.energy.pu.sf$normDS,pch=2,cex=1.4,col="#CC5500"); abline(km.lm.dc.sf, lwd=3);abline(hm.lm.dc.sf, lwd=3);abline(km.lm.du.sf, col="black", lty=4, lwd=3);abline(hm.lm.du.sf, col="black", lty=4, lwd=3);title(xlab="Normalized David's Scores",line=1.25);title(ylab="Energy per unit Time", line=1.5); axis(1, at = c(0, 1, 2, 3, 4, 5, 6, 7, 8), label=rep("",9), tck=-0.015, line=0);axis(2, at = c(0.4,0.5,0.6,0.7,0.8), label=rep("",5),tck=-0.015);axis(1, at = 1:10, line = -0.8, lwd = 0, cex.axis = 1);axis(2, at = c(0.4,0.5,0.6,0.7,0.8), line = -0.7, lwd = 0, cex.axis = 1, las=1);box(col="black",lwd=3)
dev.off()


plot(total.energy.cp.sf$energy_over_time~total.energy.cp.sf$normDS,pch=1,cex=1.4,xaxt="n",yaxt="n",col="blue",xlab="",ylab="",main="",ylim=c(0.4,0.8),xlim=c(0.85,8.25),las=1); points(total.energy.pu.sf$energy_over_time~total.energy.pu.sf$normDS,pch=2,cex=1.4,col="#CC5500"); abline(km.lm.dc.sf, lwd=3);abline(hm.lm.dc.sf, lwd=3);abline(km.lm.du.sf, col="black", lty=4, lwd=3);abline(hm.lm.du.sf, col="black", lty=4, lwd=3);title(xlab="Normalized David's Scores",line=1.25);title(ylab="Energy per unit Time", line=1.5); axis(1, at = c(0, 1, 2, 3, 4, 5, 6, 7, 8), label=rep("",9), tck=-0.015, line=0);axis(2, at = c(0.4,0.5,0.6,0.7,0.8), label=rep("",5),tck=-0.015);axis(1, at = 1:10, line = -0.8, lwd = 0, cex.axis = 1);axis(2, at = c(0.4,0.5,0.6,0.7,0.8), line = -0.7, lwd = 0, cex.axis = 1, las=1);box(col="black",lwd=3)





##AVOID TRIANGLE TRANSITIVITY FIGURE
setwd("~/Desktop")
addline_format <- function(x,...){
    gsub('\\s','\n',x)
}


sf.avoid.triangle.transitivity.fig <- overall.deter.sf.avoids %>%
  ggplot( aes(x=combo2, y=triangle.transitivity,color=distribution)) +
  geom_boxplot(outlier.shape=NA) +
    geom_point(aes(shape=distribution),size=2.5,position=position_dodge(width=0.75))+
    scale_shape_manual(values=c(1, 2))+
    xlab("")+
    ylab("Triangle Transitivity") +
    theme_bw() +
    theme(panel.grid.major.x = element_line(color = "grey",size = 0.3,linetype = 2),legend.position="none",panel.grid.major = element_blank(), panel.grid.minor = element_blank(),axis.text.x=element_text(size=13, colour="black"),axis.text.y=element_text(size=12, colour="black"), panel.border=element_rect(colour="black", size=1, fill=NA), axis.title.y=element_text(size=14))+    scale_color_manual(values = c("blue","#CC5500")) +
    scale_x_discrete(limit=c("mutual rhp", "mutual history"), labels=c("RHP", "Experience"))  + 
    annotate(geom="text", x=c(1.5, 3.5, 5.5), y=-0.63, label=c("Mutual"), size=5)+
    coord_cartesian(expand=F, clip="off", xlim=c(0.25, 2.75), ylim=c(-0.5, 1.05))
jpeg("sf.avoid.triangle.transitivity.fig.jpeg", 369.6, 336)
sf.avoid.triangle.transitivity.fig
dev.off()


##AVOID DCI FIGURE
avoid.sf.dci.fig <- overall.deter.sf.avoids %>%
  ggplot( aes(x=combo2, y=dci,color=distribution)) +
geom_boxplot(outlier.shape=NA) +
    geom_point(aes(shape=distribution),size=2.5,position=position_dodge(width=0.75))+
    scale_shape_manual(values=c(1, 2))+
    xlab("")+
    ylab("Directional Consistency Index") +
    theme_bw() +
    theme(panel.grid.major.x = element_line(color = "grey",size = 0.3,linetype = 2),legend.position="none",panel.grid.major = element_blank(), panel.grid.minor = element_blank(),axis.text.x=element_text(size=13, colour="black"),axis.text.y=element_text(size=12, colour="black"), panel.border=element_rect(colour="black", size=1, fill=NA), axis.title.y=element_text(size=14))+    scale_color_manual(values = c("blue","#CC5500")) +
    scale_x_discrete(limit=c("mutual rhp", "mutual history"), labels=c("RHP", "Experience"))  + 
    annotate(geom="text", x=c(1.5, 3.5, 5.5), y=-0.14, label=c("Mutual"), size=5)+
    coord_cartesian(expand=F, clip="off", xlim=c(0.25, 2.75), ylim=c(-0.05,1.05))
jpeg("avoid.sf.dci.fig.jpeg", 369.6, 336)
avoid.sf.dci.fig
dev.off()


##AVOID STEEPNESS FIGURE
setwd("~/Desktop")
addline_format <- function(x,...){
    gsub('\\s','\n',x)
}    
avoid.sf.steep.fig <- overall.deter.sf.avoids %>%
  ggplot( aes(x=combo2, y=abs(steepness),color=distribution)) +
  geom_boxplot(outlier.shape=NA) +
    geom_point(aes(shape=distribution),size=2.5,position=position_dodge(width=0.75))+
    scale_shape_manual(values=c(1, 2))+
    xlab("")+
    ylab("Steepness") +
    theme_bw() +
    theme(panel.grid.major.x = element_line(color = "grey",size = 0.3,linetype = 2),legend.position="none",panel.grid.major = element_blank(), panel.grid.minor = element_blank(),axis.text.x=element_text(size=13, colour="black"),axis.text.y=element_text(size=12, colour="black"), panel.border=element_rect(colour="black", size=1, fill=NA), axis.title.y=element_text(size=14))+    scale_color_manual(values = c("blue","#CC5500")) +
    scale_x_discrete(limit=c("mutual rhp", "mutual history"), labels=c("RHP", "Experience"))  + 
    annotate(geom="text", x=c(1.5), y=-0.14, label=c("Mutual"), size=5)+
    coord_cartesian(expand=F, clip="off", xlim=c(0.25, 2.75), ylim=c(-0.05,1.05))
jpeg("avoid.sf.steep.fig.jpeg", 369.6, 336)
avoid.sf.steep.fig
dev.off()

sf.avoid.triangle.transitivity.fig
avoid.sf.dci.fig
avoid.sf.steep.fig



##ATTACK TRIANGLE TRANSITIVITY FIGURE
setwd("~/Desktop")
addline_format <- function(x,...){
    gsub('\\s','\n',x)
}

sf.attack.ttri.fig <- overall.deter.sf.attacks %>%
  ggplot( aes(x=combo2, y=triangle.transitivity,color=distribution)) +
  geom_boxplot(outlier.shape=NA) +
    geom_point(aes(shape=distribution),size=2.5,position=position_dodge(width=0.75))+
    scale_shape_manual(values=c(1, 2))+
    xlab("")+
    ylab("Triangle Transitivity") +
    theme_bw() +
    theme(panel.grid.major.x = element_line(color = "grey",size = 0.3,linetype = 2),legend.position="none",panel.grid.major = element_blank(), panel.grid.minor = element_blank(),axis.text.x=element_text(size=13, colour="black"),axis.text.y=element_text(size=12, colour="black"), panel.border=element_rect(colour="black", size=1, fill=NA), axis.title.y=element_text(size=14))+    scale_color_manual(values = c("blue","#CC5500")) +
    scale_x_discrete(limit=c("mutual rhp", "mutual history"), labels=c("RHP", "Experience"))  + 
    annotate(geom="text", x=c(1.5, 3.5, 5.5), y=-0.63, label=c("Mutual"), size=5)+
    coord_cartesian(expand=F, clip="off", xlim=c(0.25, 2.75), ylim=c(-0.5, 1.05))
jpeg("sf.attack.ttri.fig.jpeg", 369.6, 336)
sf.attack.ttri.fig
dev.off()


##ATTACK DCI FIGURE
sf.attack.dci.fig <- overall.deter.sf.attacks %>%
  ggplot( aes(x=combo2, y=dci,color=distribution)) +
geom_boxplot(outlier.shape=NA) +
    geom_point(aes(shape=distribution),size=2.5,position=position_dodge(width=0.75))+
    scale_shape_manual(values=c(1, 2))+
    xlab("")+
    ylab("Directional Consistency Index") +
    theme_bw() +
    theme(panel.grid.major.x = element_line(color = "grey",size = 0.3,linetype = 2),legend.position="none",panel.grid.major = element_blank(), panel.grid.minor = element_blank(),axis.text.x=element_text(size=13, colour="black"),axis.text.y=element_text(size=12, colour="black"), panel.border=element_rect(colour="black", size=1, fill=NA), axis.title.y=element_text(size=14))+    scale_color_manual(values = c("blue","#CC5500")) +
    scale_x_discrete(limit=c("mutual rhp", "mutual history"), labels=c("RHP", "Experience"))  + 
    annotate(geom="text", x=c(1.5, 3.5, 5.5), y=-0.14, label=c("Mutual"), size=5)+
    coord_cartesian(expand=F, clip="off", xlim=c(0.25, 2.75), ylim=c(-0.05,1.05))
jpeg("sf.attack.dci.fig.jpeg", 369.6, 336)
sf.attack.dci.fig
dev.off()


##ATTACK STEEPNESS FIGURE
setwd("~/Desktop")
addline_format <- function(x,...){
    gsub('\\s','\n',x)
}

sf.attack.steep.fig <- overall.deter.sf.attacks %>%
  ggplot( aes(x=combo2, y=abs(steepness),color=distribution)) +
  geom_boxplot(outlier.shape=NA) +
    geom_point(aes(shape=distribution),size=2.5,position=position_dodge(width=0.75))+
    scale_shape_manual(values=c(1, 2))+
    xlab("")+
    ylab("Steepness") +
    theme_bw() +
    theme(panel.grid.major.x = element_line(color = "grey",size = 0.3,linetype = 2),legend.position="none",panel.grid.major = element_blank(), panel.grid.minor = element_blank(),axis.text.x=element_text(size=13, colour="black"),axis.text.y=element_text(size=12, colour="black"), panel.border=element_rect(colour="black", size=1, fill=NA), axis.title.y=element_text(size=14))+    scale_color_manual(values = c("blue","#CC5500")) +
    scale_x_discrete(limit=c("mutual rhp", "mutual history"), labels=c("RHP", "Experience"))  + 
    annotate(geom="text", x=c(1.5), y=-0.14, label=c("Mutual"), size=5)+
    coord_cartesian(expand=F, clip="off", xlim=c(0.25, 2.75), ylim=c(-0.05,1.05))
jpeg("sf.attack.steep.fig.jpeg", 369.6, 336)
sf.attack.steep.fig
dev.off()

sf.attack.ttri.fig
sf.attack.dci.fig
sf.attack.steep.fig





##PROBABILITY PROPORTION OF ATTACK FIGURE

library(tidyverse)
library(ggplot2)
library(hrbrthemes)
library(viridis)
library(Rmisc)

setwd("~/Desktop")

sf.prob.prop_attack.fig<-attack.prop.sf.p.2 %>%
  ggplot( aes(x=combo2, y=as.numeric(proportion.attacking),color=resource.dist)) +
    geom_boxplot(outlier.shape=NA) +
    geom_point(aes(shape=resource.dist),size=2.5,position=position_dodge(width=0.75))+
    scale_shape_manual(values=c(1, 2))+
    xlab("")+
    ylab("Proportion of Attack") +
    theme_bw() +
    theme(panel.grid.major.x = element_line(color = "grey",size = 0.3,linetype = 2),legend.position="none",panel.grid.major = element_blank(), panel.grid.minor = element_blank(),axis.text.x=element_text(size=13, colour="black"),axis.text.y=element_text(size=12, colour="black"), panel.border=element_rect(colour="black", size=1, fill=NA), axis.title.y=element_text(size=14))+    
    scale_color_manual(values = c("blue","#CC5500")) +
    scale_x_discrete(limit=c("mutual rhp", "mutual history"), labels=c("RHP", "Experience"))  + 
    annotate(geom="text", x=c(1.5), y=0.05, label=c("Mutual"), size=5)+
    coord_cartesian(expand=F, clip="off", xlim=c(0.25, 2.75), ylim=c(0.1,0.65))
jpeg("sf.prob.prop_attack.fig.jpeg", 336, 336)
sf.prob.prop_attack.fig
dev.off()

sf.prob.prop_attack.fig



##PROBABILITY RATE OF AVOIDS FIGURE
library(tidyverse)
library(ggplot2)
library(hrbrthemes)
library(viridis)
library(Rmisc)


setwd("~/Desktop")
rate.avoids.fig<-attack.prop.sf.p.2 %>%
  ggplot( aes(x=combo2, y=rate.avoids,color=resource.dist)) +
    geom_boxplot(outlier.shape=NA) +
    geom_point(aes(shape=resource.dist),size=2.5,position=position_dodge(width=0.75))+
    scale_shape_manual(values=c(1, 2))+
    xlab("")+
    ylab("Rate of Avoids") +
    theme_bw() +
    theme(panel.grid.major.x = element_line(color = "grey",size = 0.3,linetype = 2),legend.position="none",panel.grid.major = element_blank(), panel.grid.minor = element_blank(),axis.text.x=element_text(size=13, colour="black"),axis.text.y=element_text(size=12, colour="black"), panel.border=element_rect(colour="black", size=1, fill=NA), axis.title.y=element_text(size=14))+    
    scale_color_manual(values = c("blue","#CC5500")) +
    scale_x_discrete(limit=c("mutual rhp", "mutual history"), labels=c("RHP", "Experience"))  + 
    annotate(geom="text", x=c(1.5, 3.5, 5.5), y=-0.16, label=c("Mutual"), size=5)+
    coord_cartesian(expand=F, clip="off", xlim=c(0.25, 2.75), ylim=c(-0.1,0.65))
jpeg("rate.avoids.fig.jpeg", 336, 336)
rate.avoids.fig
dev.off()

rate.avoids.fig




# PROBABILITY DATA FIGURES

##PROBABILITY RATE OF ATTACKS FIGURES
library(tidyverse)
library(ggplot2)
library(hrbrthemes)
library(viridis)
library(Rmisc)


setwd("~/Desktop")
sf.rate.attacks.fig<-attack.prop.sf.p.2 %>%
  ggplot( aes(x=combo2, y=rate.attacks,color=resource.dist)) +
    geom_boxplot(outlier.shape=NA) +
    geom_point(aes(shape=resource.dist),size=2.5,position=position_dodge(width=0.75))+
    scale_shape_manual(values=c(1, 2))+
    xlab("")+
    ylab("Rate of Attacks") +
    theme_bw() +
    theme(panel.grid.major.x = element_line(color = "grey",size = 0.3,linetype = 2),legend.position="none",panel.grid.major = element_blank(), panel.grid.minor = element_blank(),axis.text.x=element_text(size=13, colour="black"),axis.text.y=element_text(size=12, colour="black"), panel.border=element_rect(colour="black", size=1, fill=NA), axis.title.y=element_text(size=14))+    
    scale_color_manual(values = c("blue","#CC5500")) +
    scale_x_discrete(limit=c("mutual rhp", "mutual history"), labels=c("RHP", "Experience"))  + 
    annotate(geom="text", x=c(1.5, 3.5, 5.5), y=-0.16, label=c("Mutual"), size=5)+
    coord_cartesian(expand=F, clip="off", xlim=c(0.25, 2.75), ylim=c(-0.1,0.65))
jpeg("sf.rate.attacks.fig.jpeg", 336, 336)
sf.rate.attacks.fig
dev.off()

sf.rate.attacks.fig
    



##PROBABILITY TRIANGLE TRANSITIVIY FIGURES
setwd("~/Desktop")
addline_format <- function(x,...){
    gsub('\\s','\n',x)
}

sf.prob.TTri.fig <- overall.prob.sf %>%
  ggplot( aes(x=combo2, y=triangle.transitivity,color=distribution)) +
  geom_boxplot(outlier.shape=NA) +
    geom_point(aes(shape=distribution),size=2.5,position=position_dodge(width=0.75))+
    scale_shape_manual(values=c(1, 2))+
    xlab("")+
    ylab("Triangle Transitivity") +
    theme_bw() +
    theme(panel.grid.major.x = element_line(color = "grey",size = 0.3,linetype = 2),legend.position="none",panel.grid.major = element_blank(), panel.grid.minor = element_blank(),axis.text.x=element_text(size=13, colour="black"),axis.text.y=element_text(size=12, colour="black"), panel.border=element_rect(colour="black", size=1, fill=NA), axis.title.y=element_text(size=14))+    scale_color_manual(values = c("blue","#CC5500")) +
    scale_x_discrete(limit=c("mutual rhp", "mutual history"), labels=c("RHP", "Experience"))  + 
    annotate(geom="text", x=c(1.5), y=-0.15, label=c("Mutual"), size=5)+
    coord_cartesian(expand=F, clip="off", xlim=c(0.25, 2.75), ylim=c(-0.05, 1.05))
jpeg("sf.prob.TTri.fig.jpeg", 336, 336)
sf.prob.TTri.fig
dev.off()


##PROBABILITY DIRECTIONAL CONSISTENCY INDEX FIGURES
sf.prob.DCI.fig <- overall.prob.sf %>%
  ggplot( aes(x=combo2, y=dci,color=distribution)) +
geom_boxplot(outlier.shape=NA) +
    geom_point(aes(shape=distribution),size=2.5,position=position_dodge(width=0.75))+
    scale_shape_manual(values=c(1, 2))+
    xlab("")+
    ylab("Directional Consistency Index") +
    theme_bw() +
    theme(panel.grid.major.x = element_line(color = "grey",size = 0.3,linetype = 2),legend.position="none",panel.grid.major = element_blank(), panel.grid.minor = element_blank(),axis.text.x=element_text(size=13, colour="black"),axis.text.y=element_text(size=12, colour="black"), panel.border=element_rect(colour="black", size=1, fill=NA), axis.title.y=element_text(size=14))+    scale_color_manual(values = c("blue","#CC5500")) +
    scale_x_discrete(limit=c("mutual rhp", "mutual history"), labels=c("RHP", "Experience"))  + 
    annotate(geom="text", x=c(1.5, 3.5, 5.5), y=-0.15, label=c("Mutual"), size=5)+
    coord_cartesian(expand=F, clip="off", xlim=c(0.25, 2.75), ylim=c(-0.05,1.05))
jpeg("sf.prob.DCI.fig.jpeg", 336, 336)
sf.prob.DCI.fig
dev.off()
  
  
##PROBABILITY STEEPNESS FIGURES    
sf.prob.Steep.fig <- overall.prob.sf %>%
  ggplot( aes(x=combo2, y=abs(steepness),color=distribution)) +
  geom_boxplot(outlier.shape=NA) +
    geom_point(aes(shape=distribution),size=2.5,position=position_dodge(width=0.75))+
    scale_shape_manual(values=c(1, 2))+
    xlab("")+
    ylab("Steepness") +
    theme_bw() +
    theme(panel.grid.major.x = element_line(color = "grey",size = 0.3,linetype = 2),legend.position="none",panel.grid.major = element_blank(), panel.grid.minor = element_blank(),axis.text.x=element_text(size=13, colour="black"),axis.text.y=element_text(size=12, colour="black"), panel.border=element_rect(colour="black", size=1, fill=NA), axis.title.y=element_text(size=14))+    scale_color_manual(values = c("blue","#CC5500")) +
    scale_x_discrete(limit=c("mutual rhp", "mutual history"), labels=c("RHP", "Experience"))  + 
    annotate(geom="text", x=c(1.5, 3.5, 5.5), y=-0.15, label=c("Mutual"), size=5)+
    coord_cartesian(expand=F, clip="off", xlim=c(0.25, 2.75), ylim=c(-0.05,1.05))
jpeg("sf.prob.Steep.fig.jpeg", 336, 336)
sf.prob.Steep.fig
dev.off()

sf.prob.TTri.fig
sf.prob.DCI.fig
sf.prob.Steep.fig



##PROBABILITY ENERGY EFFICIENCY FIGURES
setwd("~/Desktop")
jpeg("sf.prob.energy_efficiency.fig.jpeg", 672, 336)
par(cex.axis=1, cex.lab=1.3, mar=c(2.65,2.75,0.4,0.4),family="sans")
sf.prob.energy_efficiency.fig<-plot(total.energy.cp.sf$energy_over_time~total.energy.cp.sf$normDS,pch=1,cex=1.4,xaxt="n",yaxt="n",col="blue",xlab="",ylab="",main="",ylim=c(0.4,0.8),xlim=c(0.85,8.25),las=1); points(total.energy.pu.sf$energy_over_time~total.energy.pu.sf$normDS,pch=2,cex=1.4,col="#CC5500"); abline(km.lm.dc.sf, lwd=3);abline(hm.lm.dc.sf, lwd=3);abline(km.lm.du.sf, col="black", lty=4, lwd=3);abline(hm.lm.du.sf, col="black", lty=4, lwd=3);title(xlab="Normalized David's Scores",line=1.25);title(ylab="Energy per unit Time", line=1.5); axis(1, at = c(0, 1, 2, 3, 4, 5, 6, 7, 8), label=rep("",9), tck=-0.015, line=0);axis(2, at = c(0.4,0.5,0.6,0.7,0.8), label=rep("",5),tck=-0.015);axis(1, at = 1:10, line = -0.8, lwd = 0, cex.axis = 1);axis(2, at = c(0.4,0.5,0.6,0.7,0.8), line = -0.7, lwd = 0, cex.axis = 1, las=1);box(col="black",lwd=3)
dev.off()


plot(total.energy.cp.sf$energy_over_time~total.energy.cp.sf$normDS,pch=1,cex=1.4,xaxt="n",yaxt="n",col="blue",xlab="",ylab="",main="",ylim=c(0.4,0.8),xlim=c(0.85,8.25),las=1); points(total.energy.pu.sf$energy_over_time~total.energy.pu.sf$normDS,pch=2,cex=1.4,col="#CC5500"); abline(km.lm.dc.sf, lwd=3);abline(hm.lm.dc.sf, lwd=3);abline(km.lm.du.sf, col="black", lty=4, lwd=3);abline(hm.lm.du.sf, col="black", lty=4, lwd=3);title(xlab="Normalized David's Scores",line=1.25);title(ylab="Energy per unit Time", line=1.5); axis(1, at = c(0, 1, 2, 3, 4, 5, 6, 7, 8), label=rep("",9), tck=-0.015, line=0);axis(2, at = c(0.4,0.5,0.6,0.7,0.8), label=rep("",5),tck=-0.015);axis(1, at = 1:10, line = -0.8, lwd = 0, cex.axis = 1);axis(2, at = c(0.4,0.5,0.6,0.7,0.8), line = -0.7, lwd = 0, cex.axis = 1, las=1);box(col="black",lwd=3)





##PROBABILITY AVOID TRIANGLE TRANSITIVITY FIGURES
setwd("~/Desktop")
addline_format <- function(x,...){
    gsub('\\s','\n',x)
}


sf.avoid.triangle.transitivity.fig <- overall.prob.sf.avoids %>%
  ggplot( aes(x=combo2, y=triangle.transitivity,color=distribution)) +
  geom_boxplot(outlier.shape=NA) +
    geom_point(aes(shape=distribution),size=2.5,position=position_dodge(width=0.75))+
    scale_shape_manual(values=c(1, 2))+
    xlab("")+
    ylab("Triangle Transitivity") +
    theme_bw() +
    theme(panel.grid.major.x = element_line(color = "grey",size = 0.3,linetype = 2),legend.position="none",panel.grid.major = element_blank(), panel.grid.minor = element_blank(),axis.text.x=element_text(size=13, colour="black"),axis.text.y=element_text(size=12, colour="black"), panel.border=element_rect(colour="black", size=1, fill=NA), axis.title.y=element_text(size=14))+    scale_color_manual(values = c("blue","#CC5500")) +
    scale_x_discrete(limit=c("mutual rhp", "mutual history"), labels=c("RHP", "Experience"))  + 
    annotate(geom="text", x=c(1.5, 3.5, 5.5), y=-0.63, label=c("Mutual"), size=5)+
    coord_cartesian(expand=F, clip="off", xlim=c(0.25, 2.75), ylim=c(-0.5, 1.05))
jpeg("sf.avoid.triangle.transitivity.fig.jpeg", 369.6, 336)
sf.avoid.triangle.transitivity.fig
dev.off()


##PROBABILITY AVOID DCI FIGURES
avoid.sf.dci.fig <- overall.prob.sf.avoids %>%
  ggplot( aes(x=combo2, y=dci,color=distribution)) +
geom_boxplot(outlier.shape=NA) +
    geom_point(aes(shape=distribution),size=2.5,position=position_dodge(width=0.75))+
    scale_shape_manual(values=c(1, 2))+
    xlab("")+
    ylab("Directional Consistency Index") +
    theme_bw() +
    theme(panel.grid.major.x = element_line(color = "grey",size = 0.3,linetype = 2),legend.position="none",panel.grid.major = element_blank(), panel.grid.minor = element_blank(),axis.text.x=element_text(size=13, colour="black"),axis.text.y=element_text(size=12, colour="black"), panel.border=element_rect(colour="black", size=1, fill=NA), axis.title.y=element_text(size=14))+    scale_color_manual(values = c("blue","#CC5500")) +
    scale_x_discrete(limit=c("mutual rhp", "mutual history"), labels=c("RHP", "Experience"))  + 
    annotate(geom="text", x=c(1.5, 3.5, 5.5), y=-0.14, label=c("Mutual"), size=5)+
    coord_cartesian(expand=F, clip="off", xlim=c(0.25, 2.75), ylim=c(-0.05,1.05))
jpeg("avoid.sf.dci.fig.jpeg", 369.6, 336)
avoid.sf.dci.fig
dev.off()


##PROBABILITY AVOID STEEPNESS FIGURES
setwd("~/Desktop")
addline_format <- function(x,...){
    gsub('\\s','\n',x)
}    
avoid.sf.steep.fig <- overall.prob.sf.avoids %>%
  ggplot( aes(x=combo2, y=abs(steepness),color=distribution)) +
  geom_boxplot(outlier.shape=NA) +
    geom_point(aes(shape=distribution),size=2.5,position=position_dodge(width=0.75))+
    scale_shape_manual(values=c(1, 2))+
    xlab("")+
    ylab("Steepness") +
    theme_bw() +
    theme(panel.grid.major.x = element_line(color = "grey",size = 0.3,linetype = 2),legend.position="none",panel.grid.major = element_blank(), panel.grid.minor = element_blank(),axis.text.x=element_text(size=13, colour="black"),axis.text.y=element_text(size=12, colour="black"), panel.border=element_rect(colour="black", size=1, fill=NA), axis.title.y=element_text(size=14))+    scale_color_manual(values = c("blue","#CC5500")) +
    scale_x_discrete(limit=c("mutual rhp", "mutual history"), labels=c("RHP", "Experience"))  + 
    annotate(geom="text", x=c(1.5), y=-0.14, label=c("Mutual"), size=5)+
    coord_cartesian(expand=F, clip="off", xlim=c(0.25, 2.75), ylim=c(-0.05,1.05))
jpeg("avoid.sf.steep.fig.jpeg", 369.6, 336)
avoid.sf.steep.fig
dev.off()

sf.avoid.triangle.transitivity.fig
avoid.sf.dci.fig
avoid.sf.steep.fig



##PROBABILITY ATTACK TRIANGLE TRANSITIVITY FIGURES
setwd("~/Desktop")
addline_format <- function(x,...){
    gsub('\\s','\n',x)
}

sf.attack.ttri.fig <- overall.prob.sf.attacks %>%
  ggplot( aes(x=combo2, y=triangle.transitivity,color=distribution)) +
  geom_boxplot(outlier.shape=NA) +
    geom_point(aes(shape=distribution),size=2.5,position=position_dodge(width=0.75))+
    scale_shape_manual(values=c(1, 2))+
    xlab("")+
    ylab("Triangle Transitivity") +
    theme_bw() +
    theme(panel.grid.major.x = element_line(color = "grey",size = 0.3,linetype = 2),legend.position="none",panel.grid.major = element_blank(), panel.grid.minor = element_blank(),axis.text.x=element_text(size=13, colour="black"),axis.text.y=element_text(size=12, colour="black"), panel.border=element_rect(colour="black", size=1, fill=NA), axis.title.y=element_text(size=14))+    scale_color_manual(values = c("blue","#CC5500")) +
    scale_x_discrete(limit=c("mutual rhp", "mutual history"), labels=c("RHP", "Experience"))  + 
    annotate(geom="text", x=c(1.5, 3.5, 5.5), y=-0.63, label=c("Mutual"), size=5)+
    coord_cartesian(expand=F, clip="off", xlim=c(0.25, 2.75), ylim=c(-0.5, 1.05))
jpeg("sf.attack.ttri.fig.jpeg", 369.6, 336)
sf.attack.ttri.fig
dev.off()


##PROBABILITY ATTACK DCI FIGURES
sf.attack.dci.fig <- overall.prob.sf.attacks %>%
  ggplot( aes(x=combo2, y=dci,color=distribution)) +
geom_boxplot(outlier.shape=NA) +
    geom_point(aes(shape=distribution),size=2.5,position=position_dodge(width=0.75))+
    scale_shape_manual(values=c(1, 2))+
    xlab("")+
    ylab("Directional Consistency Index") +
    theme_bw() +
    theme(panel.grid.major.x = element_line(color = "grey",size = 0.3,linetype = 2),legend.position="none",panel.grid.major = element_blank(), panel.grid.minor = element_blank(),axis.text.x=element_text(size=13, colour="black"),axis.text.y=element_text(size=12, colour="black"), panel.border=element_rect(colour="black", size=1, fill=NA), axis.title.y=element_text(size=14))+    scale_color_manual(values = c("blue","#CC5500")) +
    scale_x_discrete(limit=c("mutual rhp", "mutual history"), labels=c("RHP", "Experience"))  + 
    annotate(geom="text", x=c(1.5, 3.5, 5.5), y=-0.14, label=c("Mutual"), size=5)+
    coord_cartesian(expand=F, clip="off", xlim=c(0.25, 2.75), ylim=c(-0.05,1.05))
jpeg("sf.attack.dci.fig.jpeg", 369.6, 336)
sf.attack.dci.fig
dev.off()


##PROBABILITY ATTACK STEEPNESS FIGURES
setwd("~/Desktop")
addline_format <- function(x,...){
    gsub('\\s','\n',x)
}

sf.attack.steep.fig <- overall.prob.sf.attacks %>%
  ggplot( aes(x=combo2, y=abs(steepness),color=distribution)) +
  geom_boxplot(outlier.shape=NA) +
    geom_point(aes(shape=distribution),size=2.5,position=position_dodge(width=0.75))+
    scale_shape_manual(values=c(1, 2))+
    xlab("")+
    ylab("Steepness") +
    theme_bw() +
    theme(panel.grid.major.x = element_line(color = "grey",size = 0.3,linetype = 2),legend.position="none",panel.grid.major = element_blank(), panel.grid.minor = element_blank(),axis.text.x=element_text(size=13, colour="black"),axis.text.y=element_text(size=12, colour="black"), panel.border=element_rect(colour="black", size=1, fill=NA), axis.title.y=element_text(size=14))+    scale_color_manual(values = c("blue","#CC5500")) +
    scale_x_discrete(limit=c("mutual rhp", "mutual history"), labels=c("RHP", "Experience"))  + 
    annotate(geom="text", x=c(1.5), y=-0.14, label=c("Mutual"), size=5)+
    coord_cartesian(expand=F, clip="off", xlim=c(0.25, 2.75), ylim=c(-0.05,1.05))
jpeg("sf.attack.steep.fig.jpeg", 369.6, 336)
sf.attack.steep.fig
dev.off()

sf.attack.ttri.fig
sf.attack.dci.fig
sf.attack.steep.fig





# INITIATOR WINS DATA FIGURES

##INITIATOR WINS TRIANGLE TRANSITIVITY FIGURES
setwd("~/Desktop")
addline_format <- function(x,...){
    gsub('\\s','\n',x)
}


sf.initiator.ttri.fig <- overall.initiator.sf %>%
  ggplot( aes(x=combo2, y=abs(triangle.transitivity),color=distribution)) + 
  geom_boxplot(outlier.shape=NA) +
    geom_point(aes(shape=distribution),size=2.5,position=position_dodge(width=0.75))+
    scale_shape_manual(values=c(1, 2))+
    xlab("")+
    ylab("Triangle Transitivity") +
    theme_bw() +
    theme(panel.grid.major.x = element_line(color = "grey",size = 0.3,linetype = 2),legend.position="none",panel.grid.major = element_blank(), panel.grid.minor = element_blank(),axis.text.x=element_text(size=13, colour="black"),axis.text.y=element_text(size=12, colour="black"), panel.border=element_rect(colour="black", size=1, fill=NA), axis.title.y=element_text(size=14))+    scale_color_manual(values = c("blue","#CC5500")) +
    scale_x_discrete(limit=c("mutual rhp", "mutual history"), labels=c("RHP", "Experience"))  + 
    annotate(geom="text", x=c(1.5), y=-0.15, label=c("Mutual"), size=5)+
    coord_cartesian(expand=F, clip="off", xlim=c(0.25, 2.75), ylim=c(-0.05, 1.05))
jpeg("sf.initiator.ttri.fig.jpeg", 336, 336)
sf.initiator.ttri.fig
dev.off()

##INITIATOR WINS DCI FIGURES
sf.initiator.dci.fig <- overall.initiator.sf %>%
  ggplot( aes(x=combo2, y=dci,color=distribution)) +
geom_boxplot(outlier.shape=NA) +
    geom_point(aes(shape=distribution),size=2.5,position=position_dodge(width=0.75))+
    scale_shape_manual(values=c(1, 2))+
    xlab("")+
    ylab("Directional Consistency Index") +
    theme_bw() +
    theme(panel.grid.major.x = element_line(color = "grey",size = 0.3,linetype = 2),legend.position="none",panel.grid.major = element_blank(), panel.grid.minor = element_blank(),axis.text.x=element_text(size=13, colour="black"),axis.text.y=element_text(size=12, colour="black"), panel.border=element_rect(colour="black", size=1, fill=NA), axis.title.y=element_text(size=14))+    scale_color_manual(values = c("blue","#CC5500")) +
    scale_x_discrete(limit=c("mutual rhp", "mutual history"), labels=c("RHP", "Experience"))  + 
    annotate(geom="text", x=c(1.5, 3.5, 5.5), y=-0.15, label=c("Mutual"), size=5)+
    coord_cartesian(expand=F, clip="off", xlim=c(0.25, 2.75), ylim=c(-0.05,1.05))
jpeg("sf.initiator.dci.fig.jpeg", 336, 336)
sf.initiator.dci.fig
dev.off()
    
##INITIATOR WINS STEEPNESS FIGURES
sf.initiator.steep.fig <- overall.initiator.sf %>%
  ggplot( aes(x=combo2, y=abs(steepness),color=distribution)) +
  geom_boxplot(outlier.shape=NA) +
    geom_point(aes(shape=distribution),size=2.5,position=position_dodge(width=0.75))+
    scale_shape_manual(values=c(1, 2))+
    xlab("")+
    ylab("Steepness") +
    theme_bw() +
    theme(panel.grid.major.x = element_line(color = "grey",size = 0.3,linetype = 2),legend.position="none",panel.grid.major = element_blank(), panel.grid.minor = element_blank(),axis.text.x=element_text(size=13, colour="black"),axis.text.y=element_text(size=12, colour="black"), panel.border=element_rect(colour="black", size=1, fill=NA), axis.title.y=element_text(size=14))+    scale_color_manual(values = c("blue","#CC5500")) +
    scale_x_discrete(limit=c("mutual rhp", "mutual history"), labels=c("RHP", "Experience"))  + 
    annotate(geom="text", x=c(1.5, 3.5, 5.5), y=-0.15, label=c("Mutual"), size=5)+
    coord_cartesian(expand=F, clip="off", xlim=c(0.25, 2.75), ylim=c(-0.05,1.05))
jpeg("sf.initiator.steep.fig.jpeg", 336, 336)
sf.initiator.steep.fig
dev.off()

sf.initiator.ttri.fig
sf.initiator.dci.fig
sf.initiator.steep.fig



##INITIATOR WINS AVOID TRIANGLE TRANSITIVITY FIGURES
setwd("~/Desktop")
addline_format <- function(x,...){
    gsub('\\s','\n',x)
}

sf.initiator.ttri.avoid.fig <- overall.initiator.sf.avoids %>%
  ggplot( aes(x=combo2, y=triangle.transitivity,color=distribution)) +
  geom_boxplot(outlier.shape=NA) +
    geom_point(aes(shape=distribution),size=2.5,position=position_dodge(width=0.75))+
    scale_shape_manual(values=c(1, 2))+
    xlab("")+
    ylab("Triangle Transitivity") +
    theme_bw() +
    theme(panel.grid.major.x = element_line(color = "grey",size = 0.3,linetype = 2),legend.position="none",panel.grid.major = element_blank(), panel.grid.minor = element_blank(),axis.text.x=element_text(size=13, colour="black"),axis.text.y=element_text(size=12, colour="black"), panel.border=element_rect(colour="black", size=1, fill=NA), axis.title.y=element_text(size=14))+    scale_color_manual(values = c("blue","#CC5500")) +
    scale_x_discrete(limit=c("mutual rhp", "mutual history"), labels=c("RHP", "Experience"))  + 
    annotate(geom="text", x=c(1.5, 3.5, 5.5), y=-0.63, label=c("Mutual"), size=5)+
    coord_cartesian(expand=F, clip="off", xlim=c(0.25, 2.75), ylim=c(-0.5, 1.05))
jpeg("sf.initiator.ttri.avoid.fig.jpeg", 369.6, 336)
sf.initiator.ttri.avoid.fig
dev.off()

##INITIATOR WINS AVOID DCI FIGURES
sf.initiator.dci.avoid.fig <- overall.initiator.sf.avoids %>%
  ggplot( aes(x=combo2, y=dci,color=distribution)) +
geom_boxplot(outlier.shape=NA) +
    geom_point(aes(shape=distribution),size=2.5,position=position_dodge(width=0.75))+
    scale_shape_manual(values=c(1, 2))+
    xlab("")+
    ylab("Directional Consistency Index") +
    theme_bw() +
    theme(panel.grid.major.x = element_line(color = "grey",size = 0.3,linetype = 2),legend.position="none",panel.grid.major = element_blank(), panel.grid.minor = element_blank(),axis.text.x=element_text(size=13, colour="black"),axis.text.y=element_text(size=12, colour="black"), panel.border=element_rect(colour="black", size=1, fill=NA), axis.title.y=element_text(size=14))+    scale_color_manual(values = c("blue","#CC5500")) +
    scale_x_discrete(limit=c("mutual rhp", "mutual history"), labels=c("RHP", "Experience"))  + 
    annotate(geom="text", x=c(1.5, 3.5, 5.5), y=-0.14, label=c("Mutual"), size=5)+
    coord_cartesian(expand=F, clip="off", xlim=c(0.25, 2.75), ylim=c(-0.05,1.05))
jpeg("sf.initiator.dci.avoid.fig.jpeg", 369.6, 336)
sf.initiator.dci.avoid.fig
dev.off()

##INITIATOR WINS AVOID STEEPNESS FIGURES
setwd("~/Desktop")
addline_format <- function(x,...){
    gsub('\\s','\n',x)
}    
sf.initiator.steep.avoid.fig <- overall.initiator.sf.avoids %>%
  ggplot( aes(x=combo2, y=abs(steepness),color=distribution)) +
  geom_boxplot(outlier.shape=NA) +
    geom_point(aes(shape=distribution),size=2.5,position=position_dodge(width=0.75))+
    scale_shape_manual(values=c(1, 2))+
    xlab("")+
    ylab("Steepness") +
    theme_bw() +
    theme(panel.grid.major.x = element_line(color = "grey",size = 0.3,linetype = 2),legend.position="none",panel.grid.major = element_blank(), panel.grid.minor = element_blank(),axis.text.x=element_text(size=13, colour="black"),axis.text.y=element_text(size=12, colour="black"), panel.border=element_rect(colour="black", size=1, fill=NA), axis.title.y=element_text(size=14))+    scale_color_manual(values = c("blue","#CC5500")) +
    scale_x_discrete(limit=c("mutual rhp", "mutual history"), labels=c("RHP", "Experience"))  + 
    annotate(geom="text", x=c(1.5), y=-0.14, label=c("Mutual"), size=5)+
    coord_cartesian(expand=F, clip="off", xlim=c(0.25, 2.75), ylim=c(-0.05,1.05))
jpeg("sf.initiator.steep.avoid.fig.jpeg", 369.6, 336)
sf.initiator.steep.avoid.fig
dev.off()

sf.initiator.ttri.avoid.fig
sf.initiator.dci.avoid.fig
sf.initiator.steep.avoid.fig



##INITIATOR WINS ATTACKS TRIANGLE TRANSITIVITY FIGURES
setwd("~/Desktop")
addline_format <- function(x,...){
    gsub('\\s','\n',x)
}

sf.initiator.ttri.attack <- overall.initiator.sf.attacks %>%
  ggplot( aes(x=combo2, y=triangle.transitivity,color=distribution)) +
  geom_boxplot(outlier.shape=NA) +
    geom_point(aes(shape=distribution),size=2.5,position=position_dodge(width=0.75))+
    scale_shape_manual(values=c(1, 2))+
    xlab("")+
    ylab("Triangle Transitivity") +
    theme_bw() +
    theme(panel.grid.major.x = element_line(color = "grey",size = 0.3,linetype = 2),legend.position="none",panel.grid.major = element_blank(), panel.grid.minor = element_blank(),axis.text.x=element_text(size=13, colour="black"),axis.text.y=element_text(size=12, colour="black"), panel.border=element_rect(colour="black", size=1, fill=NA), axis.title.y=element_text(size=14))+    scale_color_manual(values = c("blue","#CC5500")) +
    scale_x_discrete(limit=c("mutual rhp", "mutual history"), labels=c("RHP", "Experience"))  + 
    annotate(geom="text", x=c(1.5, 3.5, 5.5), y=-0.63, label=c("Mutual"), size=5)+
    coord_cartesian(expand=F, clip="off", xlim=c(0.25, 2.75), ylim=c(-0.5, 1.05))
jpeg("sf.initiator.ttri.attack.jpeg", 369.6, 336)
sf.initiator.ttri.attack
dev.off()


##INITIATOR WINS ATTACKS DCI FIGURES
sf.initiator.dci.attack <- overall.initiator.sf.attacks %>%
  ggplot( aes(x=combo2, y=dci,color=distribution)) +
geom_boxplot(outlier.shape=NA) +
    geom_point(aes(shape=distribution),size=2.5,position=position_dodge(width=0.75))+
    scale_shape_manual(values=c(1, 2))+
    xlab("")+
    ylab("Directional Consistency Index") +
    theme_bw() +
    theme(panel.grid.major.x = element_line(color = "grey",size = 0.3,linetype = 2),legend.position="none",panel.grid.major = element_blank(), panel.grid.minor = element_blank(),axis.text.x=element_text(size=13, colour="black"),axis.text.y=element_text(size=12, colour="black"), panel.border=element_rect(colour="black", size=1, fill=NA), axis.title.y=element_text(size=14))+    scale_color_manual(values = c("blue","#CC5500")) +
    scale_x_discrete(limit=c("mutual rhp", "mutual history"), labels=c("RHP", "Experience"))  + 
    annotate(geom="text", x=c(1.5, 3.5, 5.5), y=-0.14, label=c("Mutual"), size=5)+
    coord_cartesian(expand=F, clip="off", xlim=c(0.25, 2.75), ylim=c(-0.05,1.05))
jpeg("sf.initiator.dci.attack.jpeg", 369.6, 336)
sf.initiator.dci.attack
dev.off()


##INITIATOR WINS ATTACKS STEEPNESS FIGURES
setwd("~/Desktop")
addline_format <- function(x,...){
    gsub('\\s','\n',x)
}
sf.initiator.steep.attack <- overall.initiator.sf.attacks %>%
  ggplot( aes(x=combo2, y=abs(steepness),color=distribution)) +
  geom_boxplot(outlier.shape=NA) +
    geom_point(aes(shape=distribution),size=2.5,position=position_dodge(width=0.75))+
    scale_shape_manual(values=c(1, 2))+
    xlab("")+
    ylab("Steepness") +
    theme_bw() +
    theme(panel.grid.major.x = element_line(color = "grey",size = 0.3,linetype = 2),legend.position="none",panel.grid.major = element_blank(), panel.grid.minor = element_blank(),axis.text.x=element_text(size=13, colour="black"),axis.text.y=element_text(size=12, colour="black"), panel.border=element_rect(colour="black", size=1, fill=NA), axis.title.y=element_text(size=14))+    scale_color_manual(values = c("blue","#CC5500")) +
    scale_x_discrete(limit=c("mutual rhp", "mutual history"), labels=c("RHP", "Experience"))  + 
    annotate(geom="text", x=c(1.5), y=-0.14, label=c("Mutual"), size=5)+
    coord_cartesian(expand=F, clip="off", xlim=c(0.25, 2.75), ylim=c(-0.05,1.05))
jpeg("sf.initiator.steep.attack.jpeg", 369.6, 336)
sf.initiator.steep.attack
dev.off()

sf.initiator.ttri.attack
sf.initiator.dci.attack
sf.initiator.steep.attack



##INITIATOR WINS ENERGY FIGURES
setwd("~/Desktop")
jpeg("initiator.wins.sf.energy.jpeg", 672, 336)
par(cex.axis=1, cex.lab=1.3, mar=c(2.65,2.75,0.4,0.4),family="sans")

initiator.wins.sf.energy<-plot(total.energy.ci.sf$energy_over_time~total.energy.ci.sf$normDS,pch=1,cex=1.4,xaxt="n",yaxt="n",col="blue",xlab="",ylab="",main="",ylim=c(0.4,0.8),xlim=c(0.85,8.25),las=1); points(total.energy.iu.sf$energy_over_time~total.energy.iu.sf$normDS,pch=2,cex=1.4,col="#CC5500"); abline(km.lm.ci.sf, lwd=3);abline(hm.lm.ci.sf, lwd=3);abline(km.lm.ui.sf, col="black", lty=4, lwd=3);abline(hm.lm.ui.sf, col="black", lty=4, lwd=3);title(xlab="Normalized David's Scores",line=1.25);title(ylab="Energy per unit Time", line=1.5); axis(1, at = c(0, 1, 2, 3, 4, 5, 6, 7, 8), label=rep("",9), tck=-0.015, line=0);axis(2, at = c(0.4,0.5,0.6,0.7,0.8), label=rep("",5),tck=-0.015);axis(1, at = 1:10, line = -0.8, lwd = 0, cex.axis = 1);axis(2, at = c(0.4,0.5,0.6,0.7,0.8), line = -0.7, lwd = 0, cex.axis = 1, las=1);box(col="black",lwd=3)
dev.off()



##DETERMINISTIC VS. INITIATOR WINS FIGURES

initiator.wins.sf<-attack.prop.sf.i.2[attack.prop.sf.i.2$assessment.info=="history",]
rhp.initiator.prop.attack.sf<-attack.prop.sf.2[attack.prop.sf.2$assessment.info=="knowledge",]
rhp.initiator.prop.attack.sf<-rbind(rhp.initiator.prop.attack.sf, initiator.wins.sf)
setwd("~/Desktop")
addline_format <- function(x,...){
    gsub('\\s','\n',x)
}
bw.vs.iw.sf.prop.attack.figure <- rhp.initiator.prop.attack.sf %>%
  ggplot( aes(x=combo2, y=proportion.attacking,color=resource.dist)) +
  geom_boxplot(outlier.shape=NA) +
    geom_point(aes(shape=resource.dist),size=2.5,position=position_dodge(width=0.75))+
    scale_shape_manual(values=c(1, 2))+
    xlab("")+
    ylab("Proportion of Attack") +
    theme_bw() +
    theme(panel.grid.major.x = element_line(color = "grey",size = 0.3,linetype = 2),legend.position="none",panel.grid.major = element_blank(), panel.grid.minor = element_blank(),axis.text.x=element_text(size=13, colour="black"),axis.text.y=element_text(size=12, colour="black"), panel.border=element_rect(colour="black", size=1, fill=NA), axis.title.y=element_text(size=14))+    scale_color_manual(values = c("blue","#CC5500")) +
    scale_x_discrete(limit=c("mutual rhp", "mutual history"), labels=c("RHP", "Experience"))  + 
    coord_cartesian(expand=F, clip="off", xlim=c(0.25, 2.75), ylim=c(-0.05,1.05))
jpeg("bw.vs.iw.sf.prop.attack.figure.jpeg", 336, 336)
bw.vs.iw.sf.prop.attack.figure
dev.off()



rhp.initiator.sf<-overall.deter.sf[overall.deter.sf$variable=="rhp",]
rhp.initiator.sf<-rbind(rhp.initiator.sf,overall.initiator.sf[overall.initiator.sf$variable=="history",])
bw.vs.iw.sf.steep.figure <- rhp.initiator.sf %>%
  ggplot( aes(x=combo2, y=abs(steepness),color=distribution)) +
  geom_boxplot(outlier.shape=NA) +
    geom_point(aes(shape=distribution),size=2.5,position=position_dodge(width=0.75))+
    scale_shape_manual(values=c(1, 2))+
    xlab("")+
    ylab("Steepness") +
    theme_bw() +
    theme(panel.grid.major.x = element_line(color = "grey",size = 0.3,linetype = 2),legend.position="none",panel.grid.major = element_blank(), panel.grid.minor = element_blank(),axis.text.x=element_text(size=13, colour="black"),axis.text.y=element_text(size=12, colour="black"), panel.border=element_rect(colour="black", size=1, fill=NA), axis.title.y=element_text(size=14)) +    
    scale_color_manual(values = c("blue","#CC5500")) +
    scale_x_discrete(limit=c("mutual rhp", "mutual history"), labels=c("RHP", "Experience"))  + 
    annotate(geom="text", x=c(0.375, 3.5, 5.5), y=0.99, label=c("A"), size=6, fontface="bold")+
    coord_cartesian(expand=F, clip="off", xlim=c(0.25, 2.75), ylim=c(-0.05,1.05))
jpeg("bw.vs.iw.sf.steep.figure.jpeg", 336, 336)
bw.vs.iw.sf.steep.figure
dev.off()



rhp.initiator.sf.attacks<-overall.deter.sf.attacks[overall.deter.sf.attacks$variable=="rhp",]
rhp.initiator.sf.attacks<-rbind(rhp.initiator.sf.attacks,overall.initiator.sf.attacks[overall.initiator.sf.attacks$variable=="history",])
bw.vs.iw.sf.attacks.steep.figure <- rhp.initiator.sf.attacks %>%
  ggplot( aes(x=combo2, y=abs(steepness),color=distribution)) +
  geom_boxplot(outlier.shape=NA) +
    geom_point(aes(shape=distribution),size=2.5,position=position_dodge(width=0.75))+
    scale_shape_manual(values=c(1, 2))+
    xlab("")+
    ylab("Steepness") +
    theme_bw() +
    theme(panel.grid.major.x = element_line(color = "grey",size = 0.3,linetype = 2),legend.position="none",panel.grid.major = element_blank(), panel.grid.minor = element_blank(),axis.text.x=element_text(size=13, colour="black"),axis.text.y=element_text(size=12, colour="black"), panel.border=element_rect(colour="black", size=1, fill=NA), axis.title.y=element_text(size=14))+    scale_color_manual(values = c("blue","#CC5500")) +
    scale_x_discrete(limit=c("mutual rhp", "mutual history"), labels=c("RHP", "Experience"))  + 
    annotate(geom="text", x=c(0.375, 3.5, 5.5), y=0.99, label=c("B"), size=6, fontface="bold")+
    coord_cartesian(expand=F, clip="off", xlim=c(0.25, 2.75), ylim=c(-0.05,1.05))
jpeg("bw.vs.iw.sf.attacks.steep.figure.jpeg", 336, 336)
bw.vs.iw.sf.attacks.steep.figure
dev.off()



rhp.initiator.sf.avoids<-overall.deter.sf.avoids[overall.deter.sf.avoids$variable=="rhp",]
rhp.initiator.sf.avoids<-rbind(rhp.initiator.sf.avoids,overall.initiator.sf.avoids[overall.initiator.sf.avoids$variable=="history",])
bw.vs.iw.sf.avoids.steep.figure <- rhp.initiator.sf.avoids %>%
  ggplot( aes(x=combo2, y=abs(steepness),color=distribution)) +
  geom_boxplot(outlier.shape=NA) +
    geom_point(aes(shape=distribution),size=2.5,position=position_dodge(width=0.75))+
    scale_shape_manual(values=c(1, 2))+
    xlab("")+
    ylab("Steepness") +
    theme_bw() +
    theme(panel.grid.major.x = element_line(color = "grey",size = 0.3,linetype = 2),legend.position="none",panel.grid.major = element_blank(), panel.grid.minor = element_blank(),axis.text.x=element_text(size=13, colour="black"),axis.text.y=element_text(size=12, colour="black"), panel.border=element_rect(colour="black", size=1, fill=NA), axis.title.y=element_text(size=14))+    scale_color_manual(values = c("blue","#CC5500")) +
    scale_x_discrete(limit=c("mutual rhp", "mutual history"), labels=c("RHP", "Experience"))  + 
    annotate(geom="text", x=c(0.375, 3.5, 5.5), y=0.99, label=c("C"), size=6, fontface="bold")+
    coord_cartesian(expand=F, clip="off", xlim=c(0.25, 2.75), ylim=c(-0.05,1.05))
jpeg("bw.vs.iw.sf.avoids.steep.figure.jpeg", 336, 336)
bw.vs.iw.sf.avoids.steep.figure
dev.off()


bw.vs.iw.sf.prop.attack.figure
bw.vs.iw.sf.steep.figure
bw.vs.iw.sf.attacks.steep.figure
bw.vs.iw.sf.avoids.steep.figure


##DETERMINISTIC VS. INITIATOR WINS ENERGY FIGURE
setwd("~/Desktop")
jpeg("iw.vs.bw.sf.energy.a.jpeg", 336, 336)
par(cex.axis=1, cex.lab=1.3, mar=c(2.65,2.75,0.4,0.4),family="sans")

iw.vs.bw.sf.energy.a<-{
plot(energy.km.df.cd.sf.km$energy_over_time~david.km.df.cd.sf.km$normDS,pch=1,cex=1.4,xaxt="n",yaxt="n",col="blue",xlab="",ylab="",main="",ylim=c(0.4,0.8),xlim=c(0.85,8.25),las=1);

    points(energy.km.df.ud.sf.km$energy_over_time~david.km.df.ud.sf.km$normDS,pch=2,cex=1.4,col="#CC5500");

    abline(km.lm.dc.sf, col="black", lwd=3);
    abline(km.lm.du.sf, col="black", lty=4, lwd=3);

    text(0.9, 0.795, substitute(paste(bold('A'))), cex=1.5);
    title(xlab="Normalized David's Scores",line=1.25);
    title(ylab="Energy per unit Time", line=1.5); 
    axis(1, at = c(0, 1, 2, 3, 4, 5, 6, 7, 8), label=rep("",9), tck=-0.015, line=0);
    axis(2, at = c(0.4,0.5,0.6,0.7,0.8), label=rep("",5),tck=-0.015);
    axis(1, at = 1:10, line = -0.8, lwd = 0, cex.axis = 1);
    axis(2, at = c(0.4,0.5,0.6,0.7,0.8), line = -0.7, lwd = 0, cex.axis = 1, las=1);
    box(col="black",lwd=3)
}
dev.off()



jpeg("iw.vs.bw.sf.energy.b.jpeg", 336, 336)
par(cex.axis=1, cex.lab=1.3, mar=c(2.65,2.75,0.4,0.4),family="sans")

iw.vs.bw.sf.energy.b<-{
plot(energy.hm.df.ci.sf.hm$energy_over_time~david.hm.df.ci.sf.hm$normDS,pch=1,cex=1.4,xaxt="n",yaxt="n",col="blue",xlab="",ylab="",main="",ylim=c(0.4,0.8),xlim=c(0.85,8.25),las=1);

    points(energy.hm.df.ui.sf.hm$energy_over_time~david.hm.df.ui.sf.hm$normDS,pch=2,cex=1.4,col="#CC5500"); 

    abline(hm.lm.ci.sf, lwd=3);
    abline(hm.lm.ui.sf, lty=4, lwd=3);

    text(0.9, 0.795, substitute(paste(bold('B'))), cex=1.5);
    title(xlab="Normalized David's Scores",line=1.25);
    title(ylab="Energy per unit Time", line=1.5); 
    axis(1, at = c(0, 1, 2, 3, 4, 5, 6, 7, 8), label=rep("",9), tck=-0.015, line=0);
    axis(2, at = c(0.4,0.5,0.6,0.7,0.8), label=rep("",5),tck=-0.015);
    axis(1, at = 1:10, line = -0.8, lwd = 0, cex.axis = 1);
    axis(2, at = c(0.4,0.5,0.6,0.7,0.8), line = -0.7, lwd = 0, cex.axis = 1, las=1);
    box(col="black",lwd=3)
}
dev.off()
